### ISSUE TITLE
Trouble installing at the last step

### ISSUE THREAD

**Issue by rrlawjdgns** [douglaslab/cadnano2#16]
Hello, I am having trouble installing cadnano2 at mac OS

When I ran the code: python3 main.py
The output is

Traceback (most recent call last):
  File "/Users/jeonghoonkim/cadnano2/./views/documentwindow.py", line 139, in moveEvent
    self.settings.beginGroup("MainWindow")
AttributeError: 'DocumentWindow' object has no attribute 'settings'
zsh: abort      python3 main.py

What should I do with this issue?

**Comment by sdouglas** [comment]
Hi, thanks for reporting this issue. 

In general, I've been suggesting that people check out other CAD tools that are actively maintained, such as [ENSnano](http://www.ens-lyon.fr/ensnano/) which seems fantastic and adds some nice features that I've always wanted to include in Cadnano. They are releasing up-to-date installers on a regular basis.

That said, I am trying to keep cadnano2 on life support. I've started a [new branch](https://github.com/douglaslab/cadnano2/tree/pyqt6) to begin porting cadnano2 to use the `PyQt6` library since it seems like that will be the only supported path forward with the newer macOS versions. So you might start there. However, installing PyQt6 (especially on an M1) can be nontrivial. I was able to do it by [duplicating the Terminal to enable the x86 rosetta feature](https://osxdaily.com/2020/11/18/how-run-homebrew-x86-terminal-apple-silicon-mac/) and then installing python3 and pyqt via homebrew.

Unfortunately, I'm finding there are many breaking changes in PyQt6 itself (especially around mouse events), and would happily accept pull requests on this branch that fix those bugs.

**Comment by sdouglas** [comment]
The PyQt6 version is now merged into the master branch and is our main release removing forward. Please try installing into a fresh virtual environment using the latest instructions in the [README](https://github.com/douglaslab/cadnano2/blob/master/README.md).

**Comment by scikat** [comment]
Hi, I'm also having the same issue/error after installing cadnano2 on macOS. I used the instructions in the linked README from the last comment above. I have attempted installation on both Intel and Apple Silicon Macs and get the same error:

The output is:

Traceback (most recent call last):
File "Users/<username>/virtualenvs/cn240/lib/python3.9/site-packages/cadnano2/views/documentwindow.py", line 139, in moveEvent
self.settings.beginGroup("MainWindow")
Attribute error: 'DocumentWindow' object has no attribute 'settings'
zsh abort cadnano2

I appreciate you keeping cadnano on life support. It is a fantastic piece of software :). 
Any ideas/feedback are welcome to try to get this working on my end, or if you have any insights. Do let me know if you need some more information to help troubleshoot.
