### ISSUE TITLE
Final step of installing cadnano2: python main.py

### ISSUE THREAD

**Issue by rannadams42** [douglaslab/cadnano2#17]
Hi, 

When I entered the command "python main.py", I keep getting this error. 

Traceback (most recent call last):
  File "C:\Users\Rebekah Adams\Documents\GitHub\cadnano2\cadnano2\main.py", line 12, in <module>
    from . import cadnano
ImportError: attempted relative import with no known parent package.

Looking forward to your response.

**Comment by sdouglas** [comment]
Hi, we are migrating to a `pip install cadnano2` workflow but I haven’t had a chance to test with Windows. Can you either try following the [Mac v4 instructions](https://douglaslab.org/tutorials/) to install, or use git to revert to commit 03af92e?

**Comment by Prateek1410** [comment]
Hello!

I am having the same issue. As an aside, we should run the 'python main.py' command in the cadnano2 folder within the cadnano2 directory where main.py file is located, right? 

I have tried both possibilities: in the cadnano2 directory, it understandably says there's no file named main.py whereas within the cadnano2 folder it shows the exactly same error that rannadams42 has posted here. 

I reverted the changes in the commit [03af92e] but the error persisted.(https://github.com/douglaslab/cadnano2/commit/03af92e65f6bd4fc880465fd06c2387d5db27a0d) 

Thank you for your time and consideration,
Prateek

**Comment by Prateek1410** [comment]
Hello!

Please help me out in this matter. I have had a new hard disk installed in my laptop so, to make some necessary changes to my structure I have to install CaDNAno. Thank you for your time and consideration and for creating such an invaluable product.

Warm Regards,
Prateek

**Comment by sdouglas** [comment]
In the process of porting to PyQt6, we have also changed the way we package and distribute cadnano2. Instead of just cloning the git repo and running "cadnano2 main.py", we are now providing a PyPI package which can be installed using just a few commands, no more downloading soruce code. Due to this change, we also use a new command to launch the app, which is just "cadnano2". 

The specific error, "ImportError: attempted relative import with no known parent package." occurs when you've install the new cadnano2 package, but are continuing to use the old method of launching the script.

Please try installing into a fresh virtual environment using the latest instructions in the [README](https://github.com/douglaslab/cadnano2/blob/master/README.md). If you have issues with the installation, please open a new issue and include your terminal output.

**Comment by Prateek1410** [comment]
Thank you so much! It works now.
