### ISSUE TITLE
Frequent crash cause

### ISSUE THREAD

**Issue by Ingersaul** [douglaslab/cadnano2#3]
Traceback (most recent call last):
  File "./views/pathview/strand/endpointitem.py", line 223, in mouseMoveEvent
    if idx != self._moveIdx:  # did we actually move?
AttributeError: 'EndpointItem' object has no attribute '_moveIdx'
Abort trap: 6

**Comment by sdouglas** [comment]
Thanks for reporting this bug. I wasn't able to reproduce the behavior, but I suspect the problem is that under some circumstances `customMouseRelease` deletes the self._moveIdx attribute, then `mouseMoveEvent` is called without a preceding `mousePressEvent` to reinitialize self._moveIdx. Instead of deleting the attribute, setting it to None (as in the constructor) should avoid this issue.
