### ISSUE TITLE
Issue in installation of Cadnano2 for Windows

### ISSUE THREAD

**Issue by Marbehzad** [douglaslab/cadnano2#51]
I've read README  but I get this error!
Can you help me with this issue please?

[
![Screenshot (405)](https://github.com/douglaslab/cadnano2/assets/146579889/d4ffca4c-515c-44c3-86a3-b9048c736e55)
](url)

**Comment by sdouglas** [comment]
This looks like a path issue. Even if cadnano2 is installed correctly, if the script is not in your path then it will fail to launch. So I would also confirm that you added the app and scripts folder to your path as described.

I cannot tell if you followed the instructions in the README. I tested cadnano2 in Windows using Python version 3.10.4. The latest version is Python 3.12.0. You appear to be running Python version 3.9, so that is one thing to check.
